### ISSUE TITLE
Publishing on NPM any time soon?

### ISSUE THREAD

**Issue by baybal** [NordicSemiconductor/bluetooth-uuid-database#2]

**Comment by dinesharjani** [comment]
Hi @baybal, the project is still in early stages and isn't ready yet for public use.

**Comment by ebaauw** [comment]
That was over 18 months ago.  Would you consider this project "ready for public use" by now?  Or at least ready for use by a home automation enthusiast who's just venturing into BLE.

**Comment by rally25rs** [comment]
I just found this repo and was happy to see all the ID numbers in one place, but surprised to find that it still hasn't been published to the npm registry. IMO it seems fairly ready for public use, since it is primarily a JSON file of IDs 🤷 Is there anything the community can do to help make this ready for use?
